Repository AY2324S1-CS2103T-F10-1/tp, pull requests merged in 2023-10, with the labels that each got.

#114 Change output name and add search by room number
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/booking/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/booking/NameContainsKeywordsPredicateTest.java
Labels: type.Task, priority.High

#145 Add prefix completion for command input.
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/prefixcompletion/PrefixCompletion.java
  src/main/java/seedu/address/logic/prefixcompletion/exceptions/PrefixCompletionException.java
  src/main/java/seedu/address/model/booking/UniqueBookingList.java
  src/main/java/seedu/address/model/booking/exceptions/BookingNotFoundException.java
  src/main/java/seedu/address/model/booking/exceptions/DuplicateRoomException.java
  src/main/java/seedu/address/model/booking/exceptions/PersonNotFoundException.java
  src/main/java/seedu/address/model/booking/exceptions/RoomNotFoundException.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/logic/prefixcompletion/PrefixCompletionTest.java
  src/test/java/seedu/address/model/booking/UniqueBookingListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Enhancement, priority.Medium

#164 Add Remarks
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/booking/Booking.java
  src/main/java/seedu/address/model/booking/Remark.java
  src/main/java/seedu/address/model/booking/exceptions/RemarkNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/BookingCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditBookingDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/prefixcompletion/PrefixCompletionTest.java
  src/test/java/seedu/address/model/booking/BookingTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBookingTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/BookingBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#165 Abstract out Prefix completion
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/prefixcompletion/AddPrefixFinder.java
  src/main/java/seedu/address/logic/prefixcompletion/PrefixCompletion.java
  src/main/java/seedu/address/logic/prefixcompletion/PrefixFinder.java
  src/test/java/seedu/address/logic/prefixcompletion/PrefixCompletionTest.java
Labels: type.Enhancement
